### ISSUE TITLE
Passing parameters

### ISSUE THREAD

**Issue by AxelFurlanF** [elevate/elevate.metabase.tools#12]
Hey, this may be a dumb question but I'm having a hard time trying to override `appsettings.json`. I've tried the following:
```
docker run elevate/elevate.metabase.tools -v appsettings.json:/app/appsettings.json Command=export OutputFilename=metabase-state.json
```
but it keeps using your sample Url.
I've even tried building the container with appsettings.json modified with my credentials but this happens:
```
Step 7/8 : COPY --from=microsoft/dotnet:2.1-sdk-alpine ./sln/metabase-exporter/bin/Debug/netcoreapp2.0/publish .
COPY failed: stat /var/lib/docker/overlay2/106b2d208102d1873443e52bfb03baec977c83d1a283fca645cb71686a58a6ae/merged/sln/metabase-exporter/bin/Debug/netcoreapp2.0/publish: no such file or directory
```

Any suggestions?
Thanks!

**Comment by mausch** [comment]
Hola! Pretty sure you need to pass an absolute path for your appsettings.json e.g. `-v $PWD/appsettings.json:/app/appsettings.json`

**Comment by AxelFurlanF** [comment]
Thanks! I ended up using another process.
