### ISSUE TITLE
Where is the exported file?

### ISSUE THREAD

**Issue by mamodo123** [elevate/elevate.metabase.tools#16]
Hello, where is the exported file? I'm running with Docker:

`sudo docker run teste Command=export OutputFilename=metabase-state.json`

but where is the file after run?

**Comment by mausch** [comment]
Hi, mount a docker volume to export it to the host filesystem e.g.

`docker run -v $PWD/pp elevate/elevate.metabase.tools command=export outputfilename=/pp/metabase-state.json`
