### ISSUE TITLE
API definitions not expecting dashboard parameters to be either a string OR a string[]

### ISSUE THREAD

**Issue by kieranbenton** [elevate/elevate.metabase.tools#19]
Pretty much as above! PR to follow...

**Comment by seocam** [comment]
I'm suffering from the same problem trying to export data from Metabase v0.36.4. I've built a container using #20 repo/branch and it seems to work fine.

**Comment by mausch** [comment]
Anyone still having issues with this? I'm currently running Metabase 0.39.1 and I'm not getting any errors exporting/importing.
