### ISSUE TITLE
Error exporting on Metabase v32

### ISSUE THREAD

**Issue by dessengov** [elevate/elevate.metabase.tools#34]
Hi there.
Whenever I run the export function on Metabase v32, I get the following error:

`Unhandled exception. System.Exception: Error initialising Metabase API for https://metabase.cogrammar.com/
 ---> metabase_exporter.MetabaseApiException: Error logging in to Metabase API. Status code: BadRequest
   at metabase_exporter.MetabaseSessionTokenManager.GetNewSessionToken() in /sln/metabase-exporter/MetabaseSessionTokenManager.cs:line 124
   at metabase_exporter.MetabaseSessionTokenManager.<InvalidateSessionToken>b__7_0() in /sln/metabase-exporter/MetabaseSessionTokenManager.cs:line 108`

I am migrating from version 32 to v48. I have tried to run on v48, and it seems to work fine.
Regards,
Dessen.

**Comment by mausch** [comment]
Hi, Metabase v0.32 is very old by now.
The current code is tested against v0.44 https://github.com/elevate/elevate.metabase.tools/blob/eb56b80805b8aefd39f28acacfbd036b6e6641c5/Tests/Tests.cs#L78

**Comment by dessengov** [comment]
Are there any other options that you are aware of that we can use to migrate from v32, from your experience?

**Comment by mausch** [comment]
Well, [v0.32 is from 2019](https://hub.docker.com/r/metabase/metabase/tags?page=&page_size=&ordering=&name=0.32), and this repo started in 2018, so maybe this used to work back then.

Also you could try upgrading Metabase in place one version at a time just in case. Make a backup of your database first of course.
